package etl.example.constants

object NameConstants {
  val ACCT_ID             = "acct_id"
  val ACCT_CCY            = "acct_ccy"
  val BAL_AFTR_BOOKG      = "bal_aftr_bookg"
  val BAL_AFTR_BOOKG_NMRC = "bal_aftr_bookg_nmrc"
  val BOOKG_AMT           = "bookg_amt"
  val BOOKG_AMT_NMRC      = "bookg_amt_nmrc"
  val BOOKG_CDT_DBT_IND   = "bookg_cdt_dbt_ind"
  val BOOKG_DT_TM_CET     = "bookg_dt_tm_cet"
  val BOOKG_DT_TM_GMT     = "bookg_dt_tm_gmt"
  val YEAR_MONTH          = "year_month"
  val BOOKING_ID          = "booking_id"
  val END_TO_END_ID       = "end_to_end_id"
  val TX_ACCT_SVCR_REF    = "tx_acct_svcr_ref"
  val NTRY_SEQ_NB         = "ntry_seq_nb"
  val CTPTY_NM            = "ctpty_nm"
  val CTPTY_CTRY          = "ctpty_ctry"
  val CTPTY_ADR_LINE1     = "ctpty_adr_line1"
  val CTPTY_ACCT_CCY      = "ctpty_acct_ccy"
  val CTPTY_ACCT_ID_BBAN  = "ctpty_acct_id_bban"
  val CTPTY_ACCT_ID_IBAN  = "ctpty_acct_id_iban"
  val CTPTY_AGT_BIC       = "ctpty_agt_bic"
  val DTLD_TX_TP          = "dtld_tx_tp"
  val RMT_INF_USTRD1      = "rmt_inf_ustrd1"
  val CSVBASE_ROW_ID      = "csvbase_row_id"
}
